# for gulp-stylelint@^5.0.0 which uses stylelint "^8.0.0"
extends: stylelint-config-standard
ignoreFiles:
  - node_modules/**/*
  - dist/**/*
plugins:
  - stylelint-scss
  - stylelint-order
rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - at-root
        - content
        - each
        - else
        - error
        - for
        - function
        - include
        - if
        - mixin
        - return
        - extend
  order/order:
    - custom-properties
    - declarations
  order/properties-alphabetical-order: true
  block-no-empty: true
  color-no-invalid-hex: true
  comment-no-empty: true
  declaration-block-no-duplicate-properties:
    - true
    - ignore: consecutive-duplicates-with-different-values
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-no-shorthand-property-overrides: true
  font-family-no-duplicate-names: true
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true
  keyframe-declaration-no-important: true
  media-feature-name-no-unknown: true
  no-empty-source: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  property-no-unknown: true
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-no-unknown: true
  selector-type-no-unknown: true
  unit-no-unknown: true
  scss/dollar-variable-pattern:
    - '^[a-z0-9]+(-[a-z0-9]+)*$'
    - ignore: local
  scss/at-function-pattern: '^[a-z0-9]+(-[a-z0-9]+)*$'
  scss/at-mixin-pattern: '^[a-z0-9]+(-[a-z0-9]+)*$'
  scss/selector-no-redundant-nesting-selector: true
  scss/at-import-no-partial-leading-underscore: true
  scss/at-else-closing-brace-newline-after: always-last-in-chain
  scss/at-else-closing-brace-space-after: always-intermediate
  scss/at-else-empty-line-before: never
  scss/at-if-closing-brace-newline-after: always-last-in-chain
  scss/at-if-closing-brace-space-after: always-intermediate
  declaration-property-unit-whitelist:
    font-size:
      - rem
      - px
      - em
      - '%'
  # stylefmt autofix supported
  color-hex-case: lower
  # declaration-block-properties-order: ?
  length-zero-no-unit: null
  number-no-trailing-zeros: true
  shorthand-property-no-redundant-values: true
  # ignore rules todo: fix these
  string-no-newline: null
  max-empty-lines: null
  comment-empty-line-before: null
  selector-pseudo-element-colon-notation: null
  no-missing-end-of-source-newline: null
  rule-empty-line-before: null
  comment-whitespace-inside: null
  # ignore stylefmt rules
  indentation: null
  number-leading-zero: null
  string-quotes: null
  color-hex-length: null
  declaration-empty-line-before: null
  declaration-colon-space-after: null
  declaration-colon-space-before: null
  at-rule-empty-line-before: null
  at-rule-semicolon-newline-after: null
  block-closing-brace-newline-after: null
  block-closing-brace-newline-before: null
  block-opening-brace-newline-after: null
  block-opening-brace-newline-before: null
  block-opening-brace-space-after: null
  block-opening-brace-space-before: null
  selector-combinator-space-after: null
  selector-combinator-space-before: null
  selector-list-comma-newline-after: null
  selector-list-comma-newline-before: null
  selector-list-comma-space-after: null
  selector-list-comma-space-before: null